# ==========================
# Document Status
# ==========================

DOCUMENT_STATUS_UPLOADED = "UPLOADED"

DOCUMENT_STATUS_OCR_COMPLETED = "OCR_COMPLETED"

DOCUMENT_STATUS_PARSED = "PARSED"

DOCUMENT_STATUS_VALIDATED = "VALIDATED"

#DOCUMENT_STATUS_TIMELINE_BUILT = "TIMELINE_BUILT"

DOCUMENT_STATUS_FRAUD_ANALYZED = "FRAUD_ANALYZED"

#DOCUMENT_STATUS_COMPLETED = "COMPLETED"

#DOCUMENT_STATUS_IN_PROGRESS = "IN_PROGRESS"