# ==========================
# Document Status
# ==========================

DOCUMENT_STATUS_UPLOADED = "UPLOADED"

DOCUMENT_STATUS_OCR_COMPLETED = "OCR_COMPLETED"

DOCUMENT_STATUS_PARSED = "PARSED"

DOCUMENT_STATUS_VALIDATED = "VALIDATED"

#DOCUMENT_STATUS_TIMELINE_BUILT = "TIMELINE_BUILT"

DOCUMENT_STATUS_FRAUD_ANALYZED = "FRAUD_ANALYZED"

#DOCUMENT_STATUS_COMPLETED = "COMPLETED"

#DOCUMENT_STATUS_IN_PROGRESS = "IN_PROGRESS"

# app/constants/travel_status.py

# app/constants/travel_status.py

TRAVEL_STATUS_PROCESSING = "PROCESSING"

TRAVEL_STATUS_COMPLETED = "COMPLETED"

TRAVEL_STATUS_FAILED = "FAILED"

TRAVEL_STATUS_MANUAL_REVIEW = "MANUAL_REVIEW"